### PR TITLE
add cosmote EPG parser

### PR DESCRIPTION
**Pull request by KODIKAS-NL**
I created a cosmote parser based on the digea for these 15 channels :
https://www.cosmotetv.gr/portal/residential/program?p_p_id=dayprogram_WAR_OTETVportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&_dayprogram_WAR_OTETVportlet_date=09-04-2023&_dayprogram_WAR_OTETVportlet_feedType=EPG&_dayprogram_WAR_OTETVportlet_start=0&_dayprogram_WAR_OTETVportlet_end=15&_dayprogram_WAR_OTETVportlet_platform=DTH&_dayprogram_WAR_OTETVportlet_categoryId=-1

There are also 87 additional available, I can add them too if you want?
https://www.cosmotetv.gr/portal/residential/program?p_p_id=dayprogram_WAR_OTETVportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&_dayprogram_WAR_OTETVportlet_date=09-04-2023&_dayprogram_WAR_OTETVportlet_feedType=EPG&_dayprogram_WAR_OTETVportlet_start=15&_dayprogram_WAR_OTETVportlet_end=102&_dayprogram_WAR_OTETVportlet_platform=DTH&_dayprogram_WAR_OTETVportlet_categoryId=-1

### CODE REVIEW

**Comment by 1nikolas** [comment]
I don't think we need -cosmote on the epg name

**Comment by KODIKAS-NL** [comment]
> I don't think we need -cosmote on the epg name

I added that because of the overlap in channels with other parsers

**Comment by 1nikolas** [comment]
> > I don't think we need -cosmote on the epg name
> 
> I added that because of the overlap in channels with other parsers, won't it create an issue if removed?

Why would we need multiple sources? I think we can remove the ertflix ones they tend to be unstable

**Comment by KODIKAS-NL** [comment]
argh, it m

> > > I don't think we need -cosmote on the epg name
> > 
> > 
> > I added that because of the overlap in channels with other parsers, won't it create an issue if removed?
> 
> Why would we need multiple sources? I think we can remove the ertflix ones they tend to be unstable

alright, I'll update the branch.
I just changed it to only replace ert 1,2,3 but I'll see if I can replace the others too

**Comment by KODIKAS-NL** [comment]
Hmm, I think we should leave it to Ert 1,2,3 only.
The data is not that good, there are gaps around the day change that shouldn't be there, in my own app it looks like this:
image
Ert 1 and Ert 3 have holes between 23:00 to 00:00 and 23:15 to 23:45 (times are CET)

I checked at cosmotetv.gr and there you see the same issue:
April 9th:
image

April 10th:
image

Also, the EPG data has not program description, just a title.

What do you think?

**Comment by 1nikolas** [comment]
I think for now just do the cosmote channels (sports & cinema) which are highly requested since the is fixed (as far as I can tell) and then we can enable ert from cosmote if we need.

**Comment by KODIKAS-NL** [comment]
> I think for now just do the cosmote channels (sports & cinema) which are highly requested since ertflix is fixed (as far as I can tell) and then we can enable ert from cosmote if we need later.

Ertflix still gives me errors on ert1,2,3 so I left them in.
image

I added the cinema & sport channels, I also took the liberty to add a "reference" directory. It contains a json file with an overview of all 102 channel which are in the cosmote feed with only the names + id which I extracted from the data, in case you want to add more 😊

**Comment by 1nikolas** [comment]
Thanks! Ert works from the site and I think they changed something up, I'll look into it later.

**Pull request merged**
